Car360/Models/Product.cs
using System.ComponentModel.DataAnnotations;

namespace Car360.Models
{
    public class Product
    {
        [Key]
        public int p_id { get; set; }
        public string p_company { get; set; }
        public string p_name { get; set; }
        public string p_price { get; set; }
        public string p_model { get; set; }
        public string p_image { get; set; }
        public int p_status { get; set; }

        public Product() 
        {
            p_status = 1;
        }
    }
}

Car360/Models/Sign.cs
using System.ComponentModel.DataAnnotations;

namespace Car360.Models
{
    public class Sign
    {
        [Key]
        public int s_id { get; set; }
        public string s_name { get; set; }
        public string s_user { get; set; }
        public string s_mail { get; set; }
        public string s_phone { get; set; }
        public string s_image { get; set; }
        public string s_pass { get; set; }
        public int s_status { get; set; }
        public List<Buy> Buyone { get; set; }

        public Sign() 
        {
            s_status = 1;
        }

    }
}

Car360/Controllers/SignController.cs
using Car360.Contexts;
using Car360.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Car360.Controllers
{
    public class SignController : Controller
    {
        private readonly MyContext _context;
        private readonly IWebHostEnvironment _env;

        public SignController(MyContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index() => View();

        public IActionResult Gallery() => View();

        public IActionResult Feedback() => View();

        public IActionResult About() => View();

        public IActionResult Sign() => View();

        [HttpPost]
        public async Task<IActionResult> Sign(IFormFile s_image, string s_user, string s_mail, string s_phone, Sign user)
        {
            if (s_image == null || user == null)
            {
                ViewBag.image = "*Image is required";
                return View();
            }

            string extension = Path.GetExtension(s_image.FileName)?.ToLower();
            if (extension != ".jpg" && extension != ".png")
            {
                ViewBag.image = "*Only jpg or png image allowed";
                return View();
            }

            var existingUser = _context.tbl_sign.FirstOrDefault(u =>
                u.s_user == s_user || u.s_mail == s_mail || u.s_phone == s_phone);

            if (existingUser != null)
            {
                ViewBag.user = existingUser.s_user == s_user ? "*Username already taken" : null;
                ViewBag.mail = existingUser.s_mail == s_mail ? "*Email already taken" : null;
                ViewBag.phone = existingUser.s_phone == s_phone ? "*Phone already taken" : null;
                return View();
            }

            string dirPath = Path.Combine(_env.WebRootPath, "User-image", s_mail);
            Directory.CreateDirectory(dirPath);

            string filePath = Path.Combine(dirPath, Path.GetFileName(s_image.FileName));
            using (var stream = new FileStream(filePath, FileMode.Create))
            {
                await s_image.CopyToAsync(stream);
            }

            user.s_image = s_image.FileName;
            _context.tbl_sign.Add(user);
            await _context.SaveChangesAsync();

            TempData["signup"] = "Sign Up Successfully!";
            return RedirectToAction("Login");
        }

        public IActionResult Login() => View();

        [HttpPost]
        public IActionResult Login(string txtuser, string txtpass)
        {
            var login = _context.tbl_sign.FirstOrDefault(u => u.s_user == txtuser && u.s_pass == txtpass);

            if (login != null)
            {
                if (login.s_status == 1)
                {
                    HttpContext.Session.SetString("myuser", login.s_id.ToString());
                    TempData["loginsuccess"] = "Login Successfully!";
                    return RedirectToAction("Index");
                }
                TempData["deactive"] = "Your account has been deactivated.";
            }
            else
            {
                TempData["loginfailed"] = "Username or password is incorrect!";
            }
            return View();
        }

        public IActionResult Product()
        {
            var products = _context.tbl_product.ToList();
            return View(products);
        }

        public IActionResult Appointment(int id)
        {
            var sessionUserId = HttpContext.Session.GetString("myuser");
            if (sessionUserId == null)
            {
                TempData["loginfirst"] = "Please login first!";
                return RedirectToAction("Login");
            }

            var product = _context.tbl_product.Find(id);
            return View(product);
        }

        [HttpPost]
        public IActionResult Appointment(Buy buy)
        {
            _context.tbl_buy.Add(buy);
            _context.SaveChanges();
            TempData["Book"] = "Your appointment was booked successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Profile()
        {
            var sessionUserId = HttpContext.Session.GetString("myuser");
            if (sessionUserId == null)
            {
                TempData["loginfirst"] = "Please login first!";
                return RedirectToAction("Login");
            }

            int userId = int.Parse(sessionUserId);
            var userData = _context.tbl_sign.Where(u => u.s_id == userId).ToList();
            return View(userData);
        }

        public IActionResult ProfileUpdate(int id)
        {
            var user = _context.tbl_sign.Find(id);
            return View(user);
        }

        [HttpPost]
        public IActionResult ProfileUpdate(Sign user)
        {
            _context.tbl_sign.Update(user);
            _context.SaveChanges();
            TempData["Password"] = "Profile updated successfully!";
            return RedirectToAction("Profile");
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Remove("myuser");
            return RedirectToAction("Login");
        }
    }
}

Car360/Views/Sign/About.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- about start -->

<div class="container" id="about-container">

    <div class="row" id="about-row">

        <div class="col-12" id="about-col">
            <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="20%" height="100%" id="about-img">
            <p id="about-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus voluptates, est saepe quas harum cum commodi nobis incidunt tempora minus modi numquam soluta repellendus adipisci officia vitae ipsum. Laboriosam fugiat perspiciatis architecto? Commodi neque nemo, natus doloribus itaque omnis porro earum cumque unde dolorem reiciendis cupiditate laudantium! Qui quidem quisquam eum.</p>
        </div>

        <div class="col-12" id="about-col-r">
            <p id="about-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus voluptates, est saepe quas harum cum commodi nobis incidunt tempora minus modi numquam soluta repellendus adipisci officia vitae ipsum. Laboriosam fugiat perspiciatis architecto? Commodi neque nemo, natus doloribus itaque omnis porro earum cumque unde dolorem reiciendis cupiditate laudantium! Qui quidem quisquam eum.</p>
            <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="20%" height="100%" id="about-img-r">
        </div>

        <div class="col-12" id="about-col">
            <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="20%" height="100%" id="about-img">
            <p id="about-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus voluptates, est saepe quas harum cum commodi nobis incidunt tempora minus modi numquam soluta repellendus adipisci officia vitae ipsum. Laboriosam fugiat perspiciatis architecto? Commodi neque nemo, natus doloribus itaque omnis porro earum cumque unde dolorem reiciendis cupiditate laudantium! Qui quidem quisquam eum.</p>
        </div>

        <div class="col-12" id="about-col-r">
            <p id="about-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Natus voluptates, est saepe quas harum cum commodi nobis incidunt tempora minus modi numquam soluta repellendus adipisci officia vitae ipsum. Laboriosam fugiat perspiciatis architecto? Commodi neque nemo, natus doloribus itaque omnis porro earum cumque unde dolorem reiciendis cupiditate laudantium! Qui quidem quisquam eum.</p>
            <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="20%" height="100%" id="about-img-r">
        </div>

    </div>

</div>

<!-- about end -->

Car360/Views/Sign/Appointment.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

@using Car360.Models;
@model Product

<!-- appointment start -->

<div class="container" id="appointment-container">
    <div class="row">
        <div class="col-6">
            <form method="post" id="sign-form">
                <img src="~/asset/image/appointment1.jpg" alt="Sign Up" id="sign-img">
                <h2 id="appointment-h2">Appointment</h2>
                <div id="form-group">
                    <input type="text" value="@Model.p_company" name="b_company" id="myinput-app" required readonly>
                </div>
                <div id="form-group">
                    <input type="text" value="@Model.p_name" name="b_name" id="myinput-app" required readonly>
                </div>
                <div id="form-group">
                    <input type="text" value="@Model.p_model" name="b_model" id="myinput-app" required readonly>
                </div>
                <div id="form-group">
                    <input type="text" value="@Model.p_price" name="b_price" id="myinput-app" required readonly>
                </div>
                <div id="form-group">
                    <input type="text" value="@Context.Session.GetString("myuser")" name="User_ID" id="myinput-app" required readonly>
                </div>
                <div id="form-group">
                    <input type="date" name="b_date" id="myinput-app" class="myinput-num" required>
                </div>
                <button type="submit" id="appointment-btn"><span id="appointment-span">Book</span></button>
            </form>
        </div>
        <div class="col-6" id="map">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3618.5710750926974!2d67.19570202443158!3d24.912608293170667!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb3377b02c89ec7%3A0x8f7391d696dcb02e!2sMalir%20Cantt%20Check%20Post%20No%202%2C%20Malir%20Cantonment%2C%20Karachi%2C%20Karachi%20City%2C%20Sindh%2C%20Pakistan!5e0!3m2!1sen!2s!4v1711051062484!5m2!1sen!2s" width="100%" height="100%" style="border: 2px solid rgb(237, 123, 14);" allowfullscreen="#" loading="fast" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
    </div>
</div>

<!-- appointment end -->

Car360/Views/Sign/Feedback.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- Feedback Start -->

<div class="container" id="sign-container">
<div class="row">
<form method="post" id="sign-form">
<img src="~/asset/image/sign up.png" alt="Sign Up" id="sign-img">
<h2 id="sign-h2">Feedback</h2>
<div id="form-group">
<input type="text" placeholder="Enter Your Name:" id="myinput" pattern="[a-zA-Z]{2+}" required>
<label for="myinput" id="mylabel">Enter Your Name:</label>
</div>
<div id="form-group">
<textarea type="number" placeholder="Enter Your Feedback:" id="myinput" class="myinput-num" required></textarea>
<label for="myinput" id="mylabel">Enter Your Feedback:</label>
</div>
<button type="submit" id="sign-btn"><span id="index-span">Feedback</span></button>
</form>
</div>
</div>

<!-- Feedback End -->

Car360/Views/Sign/Gallery.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- gallery start -->

<div class="container" id="gallery-container">
    <div class="row" id="gallery-row">
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="100%" height="300px" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/rs-7.png" alt="Car's Image Loading" width="100%" height="600px" />
            </div>
        </div>
        <div class="col-lg-4 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/Supra.png" width="100%" height="600px" alt="Car's Image Loading" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/BENZ S_CLASS.jpg" width="100%" height="300px" alt="Car's Image Loading" />
            </div>
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/BMW_M4_(G82)_IMG_4183.jpg" width="100%" height="300px" alt="Car's Image Loading" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/Crown.jpg" alt="Car's Image Loading" width="100%" height="600px" />
            </div>
        </div>
    </div>
</div>

<div class="container" id="gallery-container">
    <div class="row" id="gallery-row">
        <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/audi-r8.jpg" alt="Car's Image Loading" width="100%" height="300px" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/rs-7.png" alt="Car's Image Loading" width="100%" height="600px" />
            </div>
        </div>
        <div class="col-lg-4 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/Supra.png" width="100%" height="600px" alt="Car's Image Loading" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/BENZ S_CLASS.jpg" width="100%" height="300px" alt="Car's Image Loading" />
            </div>
        </div>

        <div class="col-lg-4 mb-4 mb-lg-0">
            <div id="gallery-img">
                <img src="~/asset/image/BMW_M4_(G82)_IMG_4183.jpg" width="100%" height="300px" alt="Car's Image Loading" />
            </div>
            <div id="gallery-img">
                <img src="~/asset/image/Crown.jpg" alt="Car's Image Loading" width="100%" height="600px" />
            </div>
        </div>
    </div>
</div>

<!-- gallery end -->

Car360/Views/Sign/Index.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- index start -->
@if (TempData["loginsuccess"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["loginsuccess"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else if (TempData["Book"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["Book"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else{}
<div class="container-fluid" id="index-slider">
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active bg-dark" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" class="active bg-dark" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" class="active bg-dark" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="~/asset/image/audi-r8.jpg" class="d-block" width="100%" height="600px" alt="Car's Image Loading">
      </div>
      <div class="carousel-item">
        <img src="~/asset/image/BMW_M4_(G82)_IMG_4183.jpg" class="d-block" width="100%" height="600px" alt="Car's Image Loading">
      </div>
      <div class="carousel-item">
        <img src="~/asset/image/prius-Toyota.jpg" class="d-block" width="100%" height="600px" alt="Car's Image Loading">
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon bg-dark active" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon bg-dark active" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

<div class="container-xxl">
<div class="row" id="intro-row">
<h1 id="intro">introduction</h1>
<div class="row" id="intro-img"><img src="~/asset/image/logo.png" alt="Car's image Loading" height="600px"></div>
<div class="row"><p id="intro-text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Perferendis tenetur consectetur dolor aperiam vitae architecto obcaecati numquam. Possimus a fuga sint ratione consectetur iusto odio. Rem eveniet culpa libero eligendi cumque sapiente magnam nostrum ut expedita! Rem animi nostrum dicta soluta eius, esse quis reiciendis temporibus? Culpa necessitatibus unde earum blanditiis nostrum atque sit voluptate fuga esse eaque reprehenderit quod debitis aut repudiandae mollitia iusto, exercitationem dolorem molestias harum impedit, et, inventore provident ad praesentium? Libero ea molestiae quo et saepe, sequi eius, nam consequuntur eum velit assumenda dolore dolorem nisi ad sint dignissimos praesentium iure consectetur, natus incidunt porro maxime non. Officiis nobis cum dolorum ut unde dolores sint qui, minima adipisci, aliquam consequuntur laborum, libero corrupti ad magni sequi magnam autem eum aut! Accusamus accusantium error expedita. Optio.</p></div>
</div>
</div>

<div class="container-fluid" id="index-card-con">
<div class="row"><h1 id="intro">our top product's</h1></div>
<div class="row" id="index-row">

<div class="col-3" id="index-card">
<h1 id="index-h1">Audi R8</h1>
<div id="img-transform">
<img src="~/asset/image/audi-r8.jpg" width="100%" height="250px" alt="Car's Image Loading">
</div>
<p id="index-h2">Model:2017</p>
<p id="index-h3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae, nobis!</p>
<p id="index-h4">Price:150,00,00</p>
<a asp-action="Product" id="product-btn" class="text-decoration-none"><span id="product-span">Buy Now</span></a>
</div>

<div class="col-3" id="index-card">
<h1 id="index-h1">BMW M4</h1>
<div id="img-transform">
<img src="~/asset/image/BMW_M4_(G82)_IMG_4183.jpg" width="100%" height="250px" alt="Car's Image Loading">
</div>
<p id="index-h2">Model:2018</p>
<p id="index-h3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae, nobis!</p>
<p id="index-h4">Price:120,00,00</p>
<a asp-action="Product" id="product-btn" class="text-decoration-none"><span id="product-span">Buy Now</span></a>
</div>

<div class="col-3" id="index-card">
<h1 id="index-h1">Toyota Prius</h1>
<div id="img-transform">
<img src="~/asset/image/prius-Toyota.jpg" width="100%" height="250px" alt="Car's Image Loading">
</div>
<p id="index-h2">Model:2023</p>
<p id="index-h3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae, nobis!</p>
<p id="index-h4">Price:180,00,00</p>
<a asp-action="Product" id="product-btn" class="text-decoration-none"><span id="product-span">Buy Now</span></a>
</div>

</div>
</div>

<!-- index end -->

Car360/Views/Sign/Login.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- login start -->

@if (TempData["signup"] != null) 
{
    <div class="alert alert-success"><strong>Success: @TempData["signup"] @TempData["loginfailed"] @TempData["deactive"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else if (TempData["loginfailed"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["loginfailed"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else if (TempData["deactive"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["deactive"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else if (TempData["loginfirst"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["loginfirst"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else{}

<div class="container" id="login-container">
    <div class="row" id="sign-row">
        <form method="post" id="sign-form">
            <img src="~/asset/image/Login.jpg" alt="Login" id="login-img">
            <h2 id="login-h2">Login</h2>
            <div id="form-group">
                <input type="text" placeholder="Enter Your Username:" id="myinput" pattern="[a-zA-Z0-9]{3+}" name="txtuser" required>
                <label for="myinput" id="mylabel">Enter Your Username:</label>
            </div>
            <div id="form-group">
                <input type="password" placeholder="Enter Your Password:" id="myinput-pass" pattern="[a-zA-Z0-9]+{8+}" name="txtpass" required>
                <label for="myinput" id="mylabel-pass">Enter Your Password:</label>
                <div id="toggle-pass" onclick="showhide()"></div>
            </div>
            <button type="submit" id="login-btn"><span id="index-span">Login</span></button>
        </form>
        <h3>@ViewBag.loginfailed @ViewBag.deactive</h3>
    </div>
</div>

<!-- login end -->

Car360/Views/Sign/Product.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

@using Car360.Models;
@model List<Product>

<!-- product start -->

<div class="container-xxl" id="index-card-con">

    <div class="row" id="index-row">

        @foreach (var row in Model)
        {

            <div class="col-3" id="index-card">
                <h1 id="index-h1">@row.p_company @row.p_name</h1>
                <div id="img-transform">
                    <img src="~/Product-image/@row.p_image/@row.p_image" width="100%" height="250px" alt="Car's Image Loading">
                </div>
                <p id="index-h2">Model:@row.p_model</p>
                <p id="index-h3">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quae, nobis!</p>
                <p id="index-h4">Price:@row.p_price</p>
                <a href="@Url.Action("Appointment","Sign",new {id=row.p_id})" class="text-decoration-none" id="product-btn"><span id="product-span">Booking</span></a>
            </div>
        
        }

    </div>

</div>

<!-- product end -->

Car360/Views/Sign/Profile.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

@using Car360.Models;
@model List<Sign>

<!-- profile start -->
@if (TempData["Password"] != null)
{
    <div class="alert alert-success"><strong>Success: @TempData["Password"]</strong><button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="close"></button></div>
}
else{}

<div class="container">
    <div class="row" id="pro-row">

        <div class="col-3" id="profile-card">

            @foreach (var row in Model) 
            { 

            <h1 id="profile-h1">@row.s_name</h1>
            <div id="user-img-profile">
                <img src="~/User-image/@row.s_mail/@row.s_image" id="user-profile-image" alt="User Image Loading" width="40%" height="60%">
            </div>
            <p id="profile-h2">@row.s_user</p>
            <p id="profile-h3">@row.s_mail</p>
            <p id="profile-h4">@row.s_phone</p>
            <p id="profile-h4">@row.s_pass</p>
            <a href="@Url.Action("Logout","Sign")" class="text-decoration-none" id="profile-btn"><span id="profile-span">Logout</span></a>

            <a href="@Url.Action("ProfileUpdate","Sign",new {id=row.s_id})" class="text-decoration-none" id="profile-btn"><span id="profile-span">Update</span></a>

            }

        </div>

    </div>
</div>

<!-- profile end -->

Car360/Views/Sign/ProfileUpdate.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

@using Car360.Models;
@model Sign

<!-- Update start -->

<div class="container" id="sign-container">
    <div class="row"> 

        <form method="post" id="sign-form">
            <img src="~/asset/image/sign up.png" alt="Sign Up" id="sign-img">
            <h2 id="sign-h2">Update</h2>
            <div id="form-group">
                <input type="text" id="myinput" value="@Model.s_id" name="s_id" required hidden/>
            </div>
            <div id="form-group">
                <input type="text" id="myinput" value="@Model.s_name" name="s_name" required/>
            </div>
            <div id="form-group">
                <input type="text" placeholder="Enter Your Username:" id="myinput" value="@Model.s_user" name="s_user" readonly required>
            </div>
            <div id="form-group">
                <input type="email" placeholder="Enter Your Gmail:" id="myinput" value="@Model.s_mail" name="s_mail" required readonly>
            </div>
            <div id="form-group">
                <input type="number" placeholder="Enter Your Phone:" id="myinput" class="myinput-num" value="@Model.s_phone" name="s_phone" readonly required>
            </div>
            <div id="form-group">
                <input type="text" id="myinput" class="myinput-num" value="@Model.s_image" name="s_image" required hidden>
            </div>
            <div id="form-group">
                <input type="password" placeholder="Enter Your Password:" id="myinput-pass" value="@Model.s_pass" name="s_pass" required>
                <div id="toggle-pass" onclick="showhide()"></div>
            </div>
            <div id="form-group">
                <input type="text" id="myinput" value="@Model.s_status" name="s_status" required hidden/>
            </div>
            <button type="submit" id="sign-btn"><span id="index-span">Update</span></button>
        </form>

     }

    </div>
</div>

<!-- Update end -->

Car360/Views/Sign/Sign.cshtml
@{
    Layout = "~/Views/Shared/_LayoutSign.cshtml";
}

<!-- sign start -->

<div class="container" id="sign-container">
<div class="row">
<form method="post" enctype="multipart/form-data" id="sign-form">
<img src="~/asset/image/sign up.png" alt="Sign Up" id="sign-img">
<h2 id="sign-h2">Sign Up</h2>
<div id="form-group">
<input type="text" placeholder="Enter Your Name:" name="s_name" id="myinput" pattern="[a-zA-Z]{2+}" required>
<label for="myinput" id="mylabel">Enter Your Name:</label>
</div>
<div id="form-group">
<input type="text" placeholder="Enter Your Username:" name="s_user" id="myinput" pattern="[a-zA-Z0-9]{3+}" required>
<label for="myinput" id="mylabel">Enter Your Username:</label>
@if(ViewBag.user != null)
{
    <span id="sign-span">@ViewBag.user</span>
}
else{}
</div>
<div id="form-group">
<input type="email" placeholder="Enter Your Gmail:" name="s_mail" id="myinput" pattern="[a=z]+[0-9]+[gmail]+.+[com]+{8,30}" required>
<label for="myinput" id="mylabel">Enter Your Gmail:</label>
@if(ViewBag.mail != null)
{
    <span id="sign-span">@ViewBag.mail</span>
}
else{}
</div>
<div id="form-group">
<input type="number" placeholder="Enter Your Phone:" name="s_phone" id="myinput" class="myinput-num" pattern="[0-9]{11}" required>
<label for="myinput" id="mylabel">Enter Your Phone:</label>
@if(ViewBag.phone != null)
{
    <span id="sign-span">@ViewBag.phone</span>
}
else{}
</div>
<div id="form-group">
<input type="file" id="myinput" class="myinput-num" name="s_image" required>
@if(ViewBag.image != null)
{
    <span id="sign-span">@ViewBag.image</span>
}
else{}
</div>
<div id="form-group">
<input type="password" placeholder="Enter Your Password:"  name="s_pass" id="myinput-pass" pattern="[a-zA-Z0-9]+{8+}" required>
<label for="myinput" id="mylabel-pass">Enter Your Password:</label>
<div id="toggle-pass" onclick="showhide()"></div>
</div>
<button type="submit" id="sign-btn"><span id="index-span">Sign Up</span></button>
</form>
</div>
</div>

<!-- sign end -->